-- MySQL Script generated by MySQL Workbench
-- Thu May 16 21:32:16 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema finance_manager_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `finance_manager_db` ;

-- -----------------------------------------------------
-- Schema finance_manager_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `finance_manager_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `finance_manager_db` ;

-- -----------------------------------------------------
-- Table `finance_manager_db`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finance_manager_db`.`users` ;

CREATE TABLE IF NOT EXISTS `finance_manager_db`.`users` (
  `user_id` INT(10) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `finance_manager_db`.`budgets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finance_manager_db`.`budgets` ;

CREATE TABLE IF NOT EXISTS `finance_manager_db`.`budgets` (
  `budget_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) NOT NULL,
  `amount` DECIMAL(7,2) UNSIGNED NOT NULL,
  `month` INT(2) UNSIGNED NOT NULL,
  `year` INT(4) UNSIGNED NOT NULL,
  PRIMARY KEY (`budget_id`),
  INDEX `fk_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `finance_manager_db`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `finance_manager_db`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finance_manager_db`.`categories` ;

CREATE TABLE IF NOT EXISTS `finance_manager_db`.`categories` (
  `category_id` INT(11) NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `finance_manager_db`.`expenses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `finance_manager_db`.`expenses` ;

CREATE TABLE IF NOT EXISTS `finance_manager_db`.`expenses` (
  `expenses_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) NOT NULL,
  `category_id` INT(11) NOT NULL,
  `amount` DECIMAL(7,2) UNSIGNED NOT NULL,
  `day` INT(2) UNSIGNED NOT NULL,
  `month` INT(2) UNSIGNED NOT NULL,
  `year` INT(4) UNSIGNED NOT NULL,
  PRIMARY KEY (`expenses_id`),
  INDEX `fk_user_id_expenses_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_category_id_expenses_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_category_id_expenses`
    FOREIGN KEY (`category_id`)
    REFERENCES `finance_manager_db`.`categories` (`category_id`),
  CONSTRAINT `fk_user_id_expenses`
    FOREIGN KEY (`user_id`)
    REFERENCES `finance_manager_db`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
